spring.application.name=farmacia

spring.datasource.url=jdbc:postgresql://localhost:5432/SaludVida
spring.datasource.username=postgres
spring.datasource.password=Mateoprice10

spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.hibernate.ddl-auto=update
